#regular
name: 'Gt'
on:
  # schedule:
    # Set the schedule time
    # - cron: '0 0,12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  google:
    name: Google
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare source
        id: params
        run: |
            source="gt.txt"
            # echo "${TEXT}" > "${source}"
            # fi
            echo "source=${source}" >> "$GITHUB_OUTPUT"
      - uses: fabasoad/translation-action@main
        id: google-step
        with:
          provider: google
          lang: en-ur
          source: ${{ steps.params.outputs.text }}
      - name: Print the result
        run: echo "Translation is '${{ steps.google-step.outputs.text }}'"
        shell: sh
