name: Pup Test
on:
  workflow_dispatch:

jobs:
  Pup:
    runs-on: ubuntu-latest
    steps:
      - name: pupPak
        uses:  MuhammadTariqGigani/action-puppeteer-script@v0
        with:
          script: |
            const page = await browser.newPage();
            await page.goto('https://example.com');
            const title = await page.$eval('title', el => el.textContent);
            return title;
          run: echo '${{ steps.get-title.outputs.result }}' # This will puts `"Example Domain"`
