name: Pup Test
on:
  workflow_dispatch:

jobs:
  Pup:
    runs-on: ubuntu-latest
    steps:
      - name: pupPak
        uses:  MuhammadTariqGigani/action-puppeteer-script@main
        with:
          script: |
            const page = await browser.newPage();
            await page.goto('https://google.com');
            const title = await page.$eval('title', el => el.textContent);
            return title;
          # run: echo '${{ steps.get-title.outputs.result }}' # This will puts `"Example Domain"`
      - name: screenshots-ci-action
        uses: xxidbr9/screenshots-action@v1.1.18
        with:
          # url: https://grabify.link/7JHS10
          devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
      - uses: actions/upload-artifact@v4
        with:
          path: screenshots
          name: Download-screenshots
